<html><body>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  1  </span><span style="font-family: monospace"></span><span style="color: #cc0066;">import</span> java.util.Scanner;</pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  2  </span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  3  </span><span style="font-family: monospace">/**</span><span style="color: #0073ff; font-family: serif; "></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  4  </span><span style="font-family: monospace">   </span><span style="color: #0073ff; font-family: serif; ">This program turns an integer into its English name.</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  5  </span><span style="font-family: monospace"></span><span style="color: #0073ff; font-family: serif; "></span><span style="font-family: monospace">*/</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  6  </span><span style="font-family: monospace"></span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">class</span> IntegerName</pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  7  </span><span style="font-family: monospace">{</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">  8  </span></span><span style="font-family: monospace">   </span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">static</span> <span style="color: #cc0066;">void</span> main(String[] args)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">  9  </span></span><span style="font-family: monospace">   {  </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 10  </span></span><span style="font-family: monospace">      </span>Scanner in = <span style="color: #cc0066;">new</span> Scanner(System.in);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 11  </span></span><span style="font-family: monospace">      </span>System.out.print(<span style="color: #32e598;">&quot;Please enter a positive integer &lt; 1000: &quot;</span>);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 12  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">int</span> input = in.nextInt();</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 13  </span></span><span style="font-family: monospace">      </span>System.out.println(intName(input));</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 14  </span></span><span style="font-family: monospace">   }</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 15  </span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 16  </span><span style="font-family: monospace">   /**</span><span style="color: #0073ff; font-family: serif; "></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 17  </span><span style="font-family: monospace">      </span><span style="color: #0073ff; font-family: serif; ">Turns a number into its English name.</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 18  </span><span style="font-family: monospace">      @param number</span><span style="color: #0073ff; font-family: serif; "> a positive integer &lt; 1,000</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 19  </span><span style="font-family: monospace">      @return</span><span style="color: #0073ff; font-family: serif; "> the name of the number (e.g. &quot;two hundred seventy four&quot;)</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 20  </span><span style="font-family: monospace">   </span><span style="color: #0073ff; font-family: serif; "></span><span style="font-family: monospace">*/</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 21  </span></span><span style="font-family: monospace">   </span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">static</span> String intName(<span style="color: #cc0066;">int</span> number)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 22  </span></span><span style="font-family: monospace">   {</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 23  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">int</span> part = number; //<span style="color: #0073ff; font-family: serif; "> The part that still needs to be converted </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 24  </span></span><span style="font-family: monospace">      </span>String name = <span style="color: #32e598;">&quot;&quot;</span>; //<span style="color: #0073ff; font-family: serif; "> The name of the number</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 25  </span></span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 26  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (part &gt;= <span style="color: #66ff19;">100</span>)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 27  </span></span><span style="font-family: monospace">      {  </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 28  </span></span><span style="font-family: monospace">         </span>name = digitName(part / <span style="color: #66ff19;">100</span>) + <span style="color: #32e598;">&quot; hundred&quot;</span>;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 29  </span></span><span style="font-family: monospace">         </span>part = part % <span style="color: #66ff19;">100</span>;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 30  </span></span><span style="font-family: monospace">      }</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 31  </span></span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 32  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (part &gt;= <span style="color: #66ff19;">20</span>)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 33  </span></span><span style="font-family: monospace">      {  </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 34  </span></span><span style="font-family: monospace">         </span>name = name + <span style="color: #32e598;">&quot; &quot;</span> + tensName(part);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 35  </span></span><span style="font-family: monospace">         </span>part = part % <span style="color: #66ff19;">10</span>;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 36  </span></span><span style="font-family: monospace">      }   </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 37  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">else</span> <span style="color: #cc0066;">if</span> (part &gt;= <span style="color: #66ff19;">10</span>)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 38  </span></span><span style="font-family: monospace">      {  </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 39  </span></span><span style="font-family: monospace">         </span>name = name + <span style="color: #32e598;">&quot; &quot;</span> + teenName(part);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 40  </span></span><span style="font-family: monospace">         </span>part = <span style="color: #66ff19;">0</span>;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 41  </span></span><span style="font-family: monospace">      }</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 42  </span></span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 43  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (part &gt; <span style="color: #66ff19;">0</span>)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 44  </span></span><span style="font-family: monospace">      {</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 45  </span></span><span style="font-family: monospace">         </span>name = name + <span style="color: #32e598;">&quot; &quot;</span> + digitName(part);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 46  </span></span><span style="font-family: monospace">      }</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 47  </span></span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 48  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">return</span> name;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 49  </span></span><span style="font-family: monospace">   }</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 50  </span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 51  </span><span style="font-family: monospace">   /**</span><span style="color: #0073ff; font-family: serif; "></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 52  </span><span style="font-family: monospace">      </span><span style="color: #0073ff; font-family: serif; ">Turns a digit into its English name.</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 53  </span><span style="font-family: monospace">      @param digit</span><span style="color: #0073ff; font-family: serif; "> an integer between 1 and 9</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 54  </span><span style="font-family: monospace">      @return</span><span style="color: #0073ff; font-family: serif; "> the name of digit (&quot;one&quot; ... &quot;nine&quot;)</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 55  </span><span style="font-family: monospace">   </span><span style="color: #0073ff; font-family: serif; "></span><span style="font-family: monospace">*/</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 56  </span></span><span style="font-family: monospace">   </span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">static</span> String digitName(<span style="color: #cc0066;">int</span> digit)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 57  </span></span><span style="font-family: monospace">   {  </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 58  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">1</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;one&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 59  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">2</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;two&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 60  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">3</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;three&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 61  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">4</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;four&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 62  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">5</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;five&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 63  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">6</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;six&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 64  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">7</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;seven&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 65  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">8</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;eight&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 66  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (digit == <span style="color: #66ff19;">9</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;nine&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 67  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;&quot;</span>;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 68  </span></span><span style="font-family: monospace">   }</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 69  </span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 70  </span><span style="font-family: monospace">   /**</span><span style="color: #0073ff; font-family: serif; "></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 71  </span><span style="font-family: monospace">      </span><span style="color: #0073ff; font-family: serif; ">Turns a number between 10 and 19 into its English name.</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 72  </span><span style="font-family: monospace">      @param number</span><span style="color: #0073ff; font-family: serif; "> an integer between 10 and 19</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 73  </span><span style="font-family: monospace">      @return</span><span style="color: #0073ff; font-family: serif; "> the name of the given number (&quot;ten&quot; ... &quot;nineteen&quot;)</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 74  </span><span style="font-family: monospace">   </span><span style="color: #0073ff; font-family: serif; "></span><span style="font-family: monospace">*/</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 75  </span></span><span style="font-family: monospace">   </span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">static</span> String teenName(<span style="color: #cc0066;">int</span> number)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 76  </span></span><span style="font-family: monospace">   {  </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 77  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">10</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;ten&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 78  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">11</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;eleven&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 79  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">12</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;twelve&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 80  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">13</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;thirteen&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 81  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">14</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;fourteen&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 82  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">15</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;fifteen&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 83  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">16</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;sixteen&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 84  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">17</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;seventeen&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 85  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">18</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;eighteen&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 86  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number == <span style="color: #66ff19;">19</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;nineteen&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 87  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;&quot;</span>;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 88  </span></span><span style="font-family: monospace">   }</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 89  </span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 90  </span><span style="font-family: monospace">   /**</span><span style="color: #0073ff; font-family: serif; "></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 91  </span><span style="font-family: monospace">      </span><span style="color: #0073ff; font-family: serif; ">Gives the name of the tens part of a number between 20 and 99.</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 92  </span><span style="font-family: monospace">      @param number</span><span style="color: #0073ff; font-family: serif; "> an integer between 20 and 99</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 93  </span><span style="font-family: monospace">      @return</span><span style="color: #0073ff; font-family: serif; "> the name of the tens part of the number (&quot;twenty&quot; ... &quot;ninety&quot;)</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 94  </span><span style="font-family: monospace">   </span><span style="color: #0073ff; font-family: serif; "></span><span style="font-family: monospace">*/</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 95  </span></span><span style="font-family: monospace">   </span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">static</span> String tensName(<span style="color: #cc0066;">int</span> number)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 96  </span></span><span style="font-family: monospace">   {   </span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 97  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">90</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;ninety&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 98  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">80</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;eighty&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 99  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">70</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;seventy&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">100  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">60</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;sixty&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">101  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">50</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;fifty&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">102  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">40</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;forty&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">103  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">30</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;thirty&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">104  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">if</span> (number &gt;= <span style="color: #66ff19;">20</span>) { <span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;twenty&quot;</span>; }</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">105  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">return</span> <span style="color: #32e598;">&quot;&quot;</span>;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">106  </span></span><span style="font-family: monospace">   }</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">107  </span><span style="font-family: monospace">}</span></pre>
</body></html>
