<html><body>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  1  </span><span style="font-family: monospace">/**</span><span style="color: #0073ff; font-family: serif; "></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  2  </span><span style="font-family: monospace">   </span><span style="color: #0073ff; font-family: serif; ">This program computes the volumes of two cubes.</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  3  </span><span style="font-family: monospace"></span><span style="color: #0073ff; font-family: serif; "></span><span style="font-family: monospace">*/</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  4  </span><span style="font-family: monospace"></span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">class</span> Cubes</pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;">  5  </span><span style="font-family: monospace">{</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">  6  </span></span><span style="font-family: monospace">   </span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">static</span> <span style="color: #cc0066;">void</span> main(String[] args)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">  7  </span></span><span style="font-family: monospace">   {</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">  8  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">double</span> result1 = cubeVolume(<span style="color: #66ff19;">2</span>);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;">  9  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">double</span> result2 = cubeVolume(<span style="color: #66ff19;">10</span>);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 10  </span></span><span style="font-family: monospace">      </span>System.out.println(<span style="color: #32e598;">&quot;A cube with side length 2 has volume &quot;</span> + result1);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 11  </span></span><span style="font-family: monospace">      </span>System.out.println(<span style="color: #32e598;">&quot;A cube with side length 10 has volume &quot;</span> + result2);</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 12  </span></span><span style="font-family: monospace">   }</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 13  </span><span style="font-family: monospace"></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 14  </span><span style="font-family: monospace">   /**</span><span style="color: #0073ff; font-family: serif; "></span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 15  </span><span style="font-family: monospace">      </span><span style="color: #0073ff; font-family: serif; ">Computes the volume of a cube.</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 16  </span><span style="font-family: monospace">      @param sideLength</span><span style="color: #0073ff; font-family: serif; "> the side length of the cube</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 17  </span><span style="font-family: monospace">      @return</span><span style="color: #0073ff; font-family: serif; "> the volume</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 18  </span><span style="font-family: monospace">   </span><span style="color: #0073ff; font-family: serif; "></span><span style="font-family: monospace">*/</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 19  </span></span><span style="font-family: monospace">   </span><span style="color: #cc0066;">public</span> <span style="color: #cc0066;">static</span> <span style="color: #cc0066;">double</span> cubeVolume(<span style="color: #cc0066;">double</span> sideLength)</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 20  </span></span><span style="font-family: monospace">   {</span></pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 21  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">double</span> volume = sideLength * sideLength * sideLength;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 22  </span></span><span style="font-family: monospace">      </span><span style="color: #cc0066;">return</span> volume;</pre>
<pre style="margin: 0em;"><span style="background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 23  </span></span><span style="font-family: monospace">   }</span></pre>
<pre style="margin: 0em;background: #ededed"><span style="color: #0073ff; font-weight: bold;"> 24  </span><span style="font-family: monospace">}</span></pre>
</body></html>
